# Dockerfile.master
FROM w3m2a-base

# entrypoint 스크립트 복사 및 실행 권한 부여
COPY entrypoint-master.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY core-site.xml /opt/hadoop/etc/hadoop/core-site.xml
COPY hdfs-site.xml /opt/hadoop/etc/hadoop/hdfs-site.xml
COPY mapred-site.xml /opt/hadoop/etc/hadoop/mapred-site.xml
COPY yarn-site.xml /opt/hadoop/etc/hadoop/yarn-site.xml

ENTRYPOINT ["/entrypoint.sh"]