# Dockerfile.master
FROM w3m2b-base

# entrypoint 스크립트 복사 및 실행 권한 부여
COPY entrypoint-namenode.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY config/core-site.xml /opt/hadoop/etc/hadoop/core-site.xml
COPY config/hdfs-site.xml /opt/hadoop/etc/hadoop/hdfs-site.xml
COPY config/mapred-site.xml /opt/hadoop/etc/hadoop/mapred-site.xml
COPY config/yarn-site.xml /opt/hadoop/etc/hadoop/yarn-site.xml

ENTRYPOINT ["/entrypoint.sh"]